### ISSUE TITLE
(git/basics): Unverständlicher Satz 

### ISSUE THREAD

**Issue by ziselsberger** [kandolfp/ws22-ulg-python-git-docker#2]
Soll das "**By** submitting an empty commit message you can **abort** a commit" heißen?

https://github.com/kandolfp/ws22-ulg-python-git-docker/blob/fa102031bd1fdf23ca67e7a6d44f364d11d33099/pages/git/basics.md?plain=1#L124

**Comment by kandolfp** [comment]
Super Danke! 6efab4e2fab684d47b176933c9aae264e9be8e1b Den hätte ich nie gefunden :)
Ich hab noch ein paar gefunden...

**Comment by ziselsberger** [comment]
Hab ich gesehn :D
